package stream

import (
	"bytes"
	"fmt"
)

// MasterPlaylist is reserved for V1 ABR. MVP always serves a single variant
// playlist generated by Playlist(). This helper exists so the Logic layer
// already owns the contract and UI does not invent a second URL scheme.
func MasterPlaylist(base string, include256 bool) string {
	var b bytes.Buffer
	b.WriteString("#EXTM3U\n")
	b.WriteString("#EXT-X-VERSION:3\n")
	b.WriteString("#EXT-X-INDEPENDENT-SEGMENTS\n")
	b.WriteString("#EXT-X-STREAM-INF:BANDWIDTH=128000,CODECS=\"mp4a.40.2\"\n")
	b.WriteString(fmt.Sprintf("%s/128k/index.m3u8\n", trimSlash(base)))
	if include256 {
		b.WriteString("#EXT-X-STREAM-INF:BANDWIDTH=256000,CODECS=\"mp4a.40.2\"\n")
		b.WriteString(fmt.Sprintf("%s/256k/index.m3u8\n", trimSlash(base)))
	}
	return b.String()
}

func trimSlash(s string) string {
	for len(s) > 0 && s[len(s)-1] == '/' {
		s = s[:len(s)-1]
	}
	return s
}

func BandwidthOf(rung string) int {
	switch rung {
	case "256k":
		return 256000
	default:
		return 128000
	}
}
